### ISSUE TITLE
APIError(code=-1121): Invalid symbol

### ISSUE THREAD

**Issue by Emmevvi** [Cempek/binance_api_profit_and_loss#1]
Hi, I tried to use your script but I get this error:

`APIError(code=-1121): Invalid symbol`

cause by some ticker, for example:

'USDT','IQ','BUSD','EUR'

at line: 

`df_balance.loc[idx, 'total_in_BTC'] = (float(asset['free']) + float(asset['locked'])) * float(self.client.get_symbol_ticker(symbol = asset['asset'] + 'BTC')['price'])`

Do you have any ideas about solving it?
Thanks, Mike

Full error is:

```
Traceback (most recent call last):
  File "xxxxxxx/binance_profit_loss/live_profit_loss.py", line 17, in <module>
    all_assets , df_balance = bnc.balance()
  File "xxxxxx\binance_profit_loss\binance_class.py", line 84, in balance
    df_balance.loc[idx, 'total_in_BTC'] = (float(asset['free']) + float(asset['locked'])) * float(self.client.get_symbol_ticker(symbol = asset['asset'] + 'BTC')['price'])
  File "xxxxxxxx\lib\site-packages\binance\client.py", line 1035, in get_symbol_ticker
    return self._get('ticker/price', data=params, version=self.PRIVATE_API_VERSION)
  File "xxxxxxx\lib\site-packages\binance\client.py", line 237, in _get
    return self._request_api('get', path, signed, version, **kwargs)
  File "xxxxxxxxx\lib\site-packages\binance\client.py", line 202, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "xxxxxxxx\lib\site-packages\binance\client.py", line 197, in _request
    return self._handle_response()
  File "xxxxxxxxx\lib\site-packages\binance\client.py", line 230, in _handle_response
    raise BinanceAPIException(self.response)
binance.exceptions.BinanceAPIException: APIError(code=-1121): Invalid symbol.
```

**Comment by Cempek** [comment]
You cannot input those tickers ('USDT','IQ','BUSD','EUR'). 

It is supposed to be like these ( 'YFIIBTC','OSTBTC','XTZBTC', 'YFIIUSDT')

**Comment by stevenb9** [comment]
Cant get it to work either, same error
